<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>


  <!-- ==========================================
       ASSETRIPPER TEXTURE DECODER
       ========================================== -->

  <ItemGroup>

    <PackageReference
      Include="AssetRipper.TextureDecoder"
      Version="1.2.0" />

  </ItemGroup>


  <!-- ==========================================
       ASSETSTOOLS.NET
       ========================================== -->

  <ItemGroup>

    <Reference Include="AssetsTools.NET">
      <HintPath>..\Libs\AssetsTools.NET.dll</HintPath>
      <Private>true</Private>
    </Reference>

    <Reference Include="AssetsTools.NET.Cpp2IL">
      <HintPath>..\Libs\AssetsTools.NET.Cpp2IL.dll</HintPath>
      <Private>true</Private>
    </Reference>

    <Reference Include="AssetsTools.NET.MonoCecil">
      <HintPath>..\Libs\AssetsTools.NET.MonoCecil.dll</HintPath>
      <Private>true</Private>
    </Reference>

    <Reference Include="AssetsTools.NET.Texture">
      <HintPath>..\Libs\AssetsTools.NET.Texture.dll</HintPath>
      <Private>true</Private>
    </Reference>

  </ItemGroup>

</Project>
