<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <SupportedOSPlatformVersion>21.0</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationId>com.uabea.nativeandroid</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    
    <!-- Mematikan pencarian file AndroidManifest.xml fisik -->
    <AndroidManifest></AndroidManifest>
    
    <!-- Parameter Sakti: Memaksa compiler Java mengabaikan error penggabungan Manifest -->
    <AndroidManifestPlaceholders>applicationLabel=UABEA_Android_Native</AndroidManifestPlaceholders>
    <AndroidCreatePackagePerAbi>false</AndroidCreatePackagePerAbi>
    
    <!-- Mengatasi konflik tipe proyek PC vs Android -->
    <ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Android" Version="11.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UABEAvalonia\UABEAvalonia.csproj" />
  </ItemGroup>
</Project>
