<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <OutputType>Exe</OutputType>

    <UseMaui>false</UseMaui>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <ApplicationTitle>UABEA Android</ApplicationTitle>
    <ApplicationId>com.uabea.android</ApplicationId>

    <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
  </PropertyGroup>

<ItemGroup>
    <ProjectReference Include="..\UABEAvalonia\UABEAvalonia.csproj" />
</ItemGroup>

</Project>
