name: Build TexToolWrap Android ARM64

on:
  workflow_dispatch:

jobs:
  build-textoolwrap:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: sdkmanager "ndk;27.2.12479018"

      - name: Show NDK
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"
          ls "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" | head
