name: build textoolwrap arm

on:
  push:
    branches:
    
  workflow_dispatch:

jobs:
  inspect-native:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: |
          sdkmanager "ndk;27.2.12479018"

      - name: Set NDK
        shell: bash
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"
          echo "NDK=$ANDROID_NDK_HOME"

      - name: Inspect TexToolWrap
        shell: bash
        run: |
          echo "======================================"
          echo "PVRTexLib"
          echo "======================================"
          find UABEA/TexToolWrap/PVRTexLib \
            -maxdepth 2 -type f | sort

          echo ""
          echo "======================================"
          echo "ISPC"
          echo "======================================"
          find UABEA/TexToolWrap/ispc \
            -maxdepth 2 -type f | sort

          echo ""
          echo "======================================"
          echo "CRUNCH"
          echo "======================================"
          find UABEA/TexToolWrap/crunch \
            -maxdepth 2 -type f | sort
