name: Build UABEA Android Native APK

on:
  workflow_dispatch: # Membuat tombol manual di tab Actions GitHub untuk memulai build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'

    - name: Install Android Workload
      run: |
        dotnet workload install android

    - name: Restore Dependencies
      run: dotnet restore AVALONIAAndroid/AVALONIANdroid.csproj

    - name: Build Android Project
      run: |
        dotnet publish AVALONIAAndroid/AVALONIANdroid.csproj -c Release -r android-arm64 --no-self-contained /p:AndroidPackageFormat=apk /p:AndroidBuildApplicationPackage=true

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: UABEA-Android-Native-APK
        path: '**/bin/Release/**/publish/*.apk'
        if-no-files-found: error
