name: Locate Texture DLL

on:
  workflow_dispatch:

jobs:
  locate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find AssetsTools.NET.Texture.dll
        shell: bash
        run: |
          echo "======================================"
          echo "MENCARI AssetsTools.NET.Texture.dll"
          echo "======================================"

          find . -type f \
            -iname "AssetsTools.NET.Texture.dll" \
            -print

          echo ""
          echo "======================================"
          echo "SELESAI"
          echo "======================================"
